
services:
  workflow:
    build: .
    ports:
      - "7705:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload
 
  # Adding Elasticsearch service
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9300:9200"  # Exposing Elasticsearch on port 9300
    volumes:
      - es_data:/usr/share/elasticsearch/data  # Persistent storage for Elasticsearch data
    networks:
      - es_network
 

 
volumes:
  es_data:  # Define persistent volume for Elasticsearch data
    driver: local
 
# Create network for inter-service communication
networks:
  es_network:
    driver: bridge
